version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '1414:1414'
    environment:
      POSTGRES_PASSWORD: secret_password
      POSTGRES_USER: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
